"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

import random
def cows_and_bulls():
  #generate target number int:
  target = int("".join([str( random.randint(0,9)) for i in range(4)]))

  attempt = None

  #obtain and validate input:
  while attempt != target:
    cows = 0
    bulls = 0
    #get input:
    attempt = input("guess the 4-digit integer: ")
    
    #check block for input
    while attempt.isdigit() == False and len(attempt) == 4:
      print("That's not a 4-digit integer. try again")
      attempt = input("guess the 4-digit integer: ")

    #check input correctness:
    for i in range(0,4):
      if str(attempt)[i] == str(target)[i]:
        cows += 1
      elif str(attempt)[i] in str(target):
        bulls += 1

    #we good?
    if cows == 4:
      print("4 cows, spot on!")
      return
    else:
      print(f"Not quite! {cows} cows and {bulls} bulls")    
  
cows_and_bulls()

